server:
  port: 8081
spring:
  application:
    name: item-server
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  output:
    ansi:
      enabled: detect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

#日志配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
